Apex Test Tracker/src/objects/CI_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Configuration - Name is the namespace for this config objects</description>
    <fields>
        <fullName>Archive_Days__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Number of days to archive test and test summary results</description>
        <label>Archive Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Test_Request__c</fullName>
        <description>Date/Time of last time tests were requested to run</description>
        <inlineHelpText>Date/Time of last time tests were requested to run - set by system</inlineHelpText>
        <label>Last Test Request</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notification_Email__c</fullName>
        <description>Email address of user to notify in case of error</description>
        <inlineHelpText>Email address of user to notify in case of error</inlineHelpText>
        <label>Notification Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Test_Delay__c</fullName>
        <description># of hours to wait before running test again</description>
        <label>Test Delay</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CI Configuration</label>
</CustomObject>

Apex Test Tracker/src/objects/CI_TestResult__c.object
<CustomObject>
    <fields>
        <fullName>ClassID__c</fullName>
        <description>Class ID of this test</description>
        <label>ClassID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Error message</description>
        <inlineHelpText>Error message</inlineHelpText>
        <label>Message</label>
        <length>128000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pass__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if test passed</description>
        <label>Pass</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Test_Name__c</fullName>
        <description>Concatenated class.method name for the test</description>
        <label>Test Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CI_TestResult</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>CI_TestResult Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CI_TestResults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CI_TestCIOperations2.cls
/*The MIT License (MIT)

Copyright (c) 2015-2019 Desaware Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

@istest
public class CI_TestCIOperations2 {

    static testMethod void testApexResults1() {
	
		String managedPrefix = CI_TestCIOperations.getManagedPrefix();

		// Tell system we've already run tests once, so it will look at results
		CI_Configuration__c	config = new CI_Configuration__c(
				name= (managedPrefix==null)? 'default': managedPrefix, 
				Last_Test_Request__c=DateTime.now().addHours(-12), 
				Notification_Email__c = UserInfo.getUserEmail(),
				Archive_Days__c = 14,
				Test_Delay__c = 23);		
		CI_ConfigWrapper.saveConfig(config);
		
		// Get test class info
		Map<ID, ApexClass> testClasses = CI_Support.getApexTestClasses(managedPrefix);
		
		List<ApexTestResult> newerResults = new List<ApexTestResult>(); 
		List<ApexTestResult> olderResults = new List<ApexTestResult>(); 
		
		// Create new tests only
		for(ApexClass testClass: testClasses.values())
		{
			newerResults.add(
				new ApexTestResult(ApexClassID = testClass.id, 
				methodName='test1', Outcome='Pass', 
				TestTimeStamp = DateTime.Now().addHours(-24)));
		}
		
		CI_Support.mockNewerTestResults = newerResults;
		
		CI_Support.performCI(managedPrefix, false);
		
		List<CI_TestResult__c> savedTestRecords = 
			[Select ID, ClassID__c, Test_Name__c, Pass__c 
			from CI_TestResult__c 
			where ClassID__c in :testClasses.keyset()];

		system.AssertEquals(testclasses.size(), savedTestRecords.size());
    }

    static testMethod void testApexResults2() {
	
		String managedPrefix = CI_TestCIOperations.getManagedPrefix();

		// Tell system we've already run tests once, so it will look at results
		CI_Configuration__c	config = new CI_Configuration__c(
				name= (managedPrefix==null)? 'default': managedPrefix, 
				Last_Test_Request__c=DateTime.now().addHours(-12), 
				Notification_Email__c = UserInfo.getUserEmail(),
				Archive_Days__c = 14,
				Test_Delay__c = 23);		
		CI_ConfigWrapper.saveConfig(config);
		
		// Get test class info
		Map<ID, ApexClass> testClasses = CI_Support.getApexTestClasses(managedPrefix);
		
		List<ApexTestResult> newerResults = new List<ApexTestResult>(); 
		List<ApexTestResult> olderResults = new List<ApexTestResult>(); 
		
		// Create new tests only
		for(ApexClass testClass: testClasses.values())
		{
			newerResults.add(
				new ApexTestResult(ApexClassID = testClass.id, 
				methodName='test1', Outcome='Fail', 
				TestTimeStamp = DateTime.Now().addHours(-12)));
		}
		
		CI_Support.mockNewerTestResults = newerResults;

		// Create new tests only
		for(ApexClass testClass: testClasses.values())
		{
			olderResults.add(
				new ApexTestResult(ApexClassID = testClass.id, 
				methodName='test1', Outcome='Pass',  
				TestTimeStamp = DateTime.Now().addHours(-36)));
		}
		
		CI_Support.mockOlderTestResults = olderResults;

		CI_Support.performCI(managedPrefix, false);
		
		List<CI_TestResult__c> savedTestRecords = 
			[Select ID, ClassID__c, Test_Name__c, Pass__c 
			from CI_TestResult__c 
			where ClassID__c in :testClasses.keyset()];

		system.AssertEquals(testClasses.size(), savedTestRecords.size());

		savedTestRecords = 
			[Select ID, Message__c 
			from CI_TestResult__c 
			where ClassID__c = null];
 
		system.AssertEquals(1, savedTestRecords.size());
		system.Assert(savedTestRecords[0].Message__c !=null);
 
    }

    static testMethod void testApexResults3() {
	
		String managedPrefix = CI_TestCIOperations.getManagedPrefix();

		// Tell system we've already run tests once, so it will look at results
		CI_Configuration__c	config = new CI_Configuration__c(
				name= (managedPrefix==null)? 'default': managedPrefix, 
				Last_Test_Request__c=DateTime.now().addHours(-12), 
				Notification_Email__c = UserInfo.getUserEmail(),
				Archive_Days__c = 14,
				Test_Delay__c = 23);		
		CI_ConfigWrapper.saveConfig(config);
		
		// Get test class info
		Map<ID, ApexClass> testClasses = CI_Support.getApexTestClasses(managedPrefix);
		
		List<ApexTestResult> newerResults = new List<ApexTestResult>(); 
		
		List<ApexTestResult> olderResults = new List<ApexTestResult>(); 
		
		// Create new tests only
		for(ApexClass testClass: testClasses.values())
		{
			olderResults.add(
				new ApexTestResult(ApexClassID = testClass.id, 
				methodName='test1', Outcome='Pass',  
				TestTimeStamp = DateTime.Now().addHours(-36)));
		}
		
		CI_Support.mockOlderTestResults = olderResults;

		// This should create initial test records
		CI_Support.performCI(managedPrefix, false);

		// Create new tests only
		for(ApexClass testClass: testClasses.values())
		{
			newerResults.add(
				new ApexTestResult(ApexClassID = testClass.id, 
				methodName='test1', Outcome='Fail', 
				TestTimeStamp = DateTime.Now().addSeconds(1)));
		}
		
		CI_Support.mockOlderTestResults = null;
		CI_Support.mockNewerTestResults = newerResults;

		// This should compare against saved records
		CI_Support.performCI(managedPrefix, false);
		
		List<CI_TestResult__c> savedTestRecords = 
			[Select ID, ClassID__c, Test_Name__c, Pass__c 
			from CI_TestResult__c 
			where ClassID__c in :testClasses.keyset()];

		system.AssertEquals(testClasses.size(), savedTestRecords.size());

		savedTestRecords = 
			[Select ID, Message__c 
			from CI_TestResult__c 
			where ClassID__c = null];
 
		system.AssertEquals(1, savedTestRecords.size());
 
    }
}