Apex Test Tracker/src/objects/CI_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Configuration - Name is the namespace for this config objects</description>
    <fields>
        <fullName>Archive_Days__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Number of days to archive test and test summary results</description>
        <label>Archive Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Test_Request__c</fullName>
        <description>Date/Time of last time tests were requested to run</description>
        <inlineHelpText>Date/Time of last time tests were requested to run - set by system</inlineHelpText>
        <label>Last Test Request</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notification_Email__c</fullName>
        <description>Email address of user to notify in case of error</description>
        <inlineHelpText>Email address of user to notify in case of error</inlineHelpText>
        <label>Notification Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Test_Delay__c</fullName>
        <description># of hours to wait before running test again</description>
        <label>Test Delay</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CI Configuration</label>
</CustomObject>

Apex Test Tracker/src/objects/CI_TestResult__c.object
<CustomObject>
    <label>CI_TestResult</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>CI_TestResult Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CI_TestResults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Apex Test Tracker/src/classes/CI_TestCIOperations.cls
/*The MIT License (MIT)

Copyright (c) 2015 Desaware Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

@istest
public class CI_TestCIOperations {
    static testMethod void highLevelTest() {

		Test.startTest();
        System.schedule('ci_schedule_test_job', 
	    	CI_ScheduledDispatcher.GetSchedulerExpression(
		    	DateTime.Now().addSeconds(10)), 
	            new CI_ScheduledDispatcher());
        Test.stopTest();
    }

	// Test with actual config created
    static testMethod void highLevelTest2() {
    	String managedPrefix = getManagedPrefix();

		CI_Configuration__c	config = new CI_Configuration__c(
				name= (managedPrefix==null)? 'default': managedPrefix, 
				Last_Test_Request__c=DateTime.now().addHours(-12), 
				Notification_Email__c = UserInfo.getUserEmail(),
				Archive_Days__c = 14,
				Test_Delay__c = 23);
		insert config;
		
		Test.startTest();
        System.schedule('ci_schedule_test_job2', 
	    	CI_ScheduledDispatcher.GetSchedulerExpression(
		    	DateTime.Now().addSeconds(10)), 
	            new CI_ScheduledDispatcher());
        Test.stopTest();
    }    
    
    public static string getManagedPrefix()
    {
		Schema.DescribeSObjectResult objres = CI_TestResult__c.SObjectType.getDescribe();
		string objName = objres.getName();
		if(objName==objres.getLocalName()) return null;
		return objName.left(objName.indexOf('__'));	
    }
}